[font]
size = 17
[font.normal]
family = "FiraMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[window]
decorations = "None"
dynamic_padding = true
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0
