[env]
TERM="xterm-256color"

[font]
size = 13
[font.normal]
family = "FiraMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[mouse]
hide_when_typing = true

[window]
decorations = "None"
dynamic_padding = true
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0
